SET DATEFORMAT DMY;
USE HappiNovel

INSERT INTO BOOKMARK VALUES('1','1')
INSERT INTO BOOKMARK VALUES('2','6')
INSERT INTO BOOKMARK VALUES('3','5')
INSERT INTO BOOKMARK VALUES('4','5')
INSERT INTO BOOKMARK VALUES('5','4')
INSERT INTO BOOKMARK VALUES('2','3')
INSERT INTO BOOKMARK VALUES('5','1')
INSERT INTO BOOKMARK VALUES('6','3')
INSERT INTO BOOKMARK VALUES('9','2')
INSERT INTO BOOKMARK VALUES('3','2')
INSERT INTO BOOKMARK VALUES('7','4')
INSERT INTO BOOKMARK VALUES('1','3')
INSERT INTO BOOKMARK VALUES('3','1')
INSERT INTO BOOKMARK VALUES('2','5')
INSERT INTO BOOKMARK VALUES('7','6')
INSERT INTO BOOKMARK VALUES('4','2')
INSERT INTO BOOKMARK VALUES('9','3')

