SET DATEFORMAT DMY;
USE HappiNovel

INSERT INTO BOOKGENRES VALUES('1','1')
INSERT INTO BOOKGENRES VALUES('1','4')
INSERT INTO BOOKGENRES VALUES('1','9')
INSERT INTO BOOKGENRES VALUES('1','7')

INSERT INTO BOOKGENRES VALUES('2','5')
INSERT INTO BOOKGENRES VALUES('2','3')
INSERT INTO BOOKGENRES VALUES('2','7')
INSERT INTO BOOKGENRES VALUES('2','9')

INSERT INTO BOOKGENRES VALUES('3','2')
INSERT INTO BOOKGENRES VALUES('3','3')
INSERT INTO BOOKGENRES VALUES('3','4')
INSERT INTO BOOKGENRES VALUES('3','7')
INSERT INTO BOOKGENRES VALUES('3','8')

INSERT INTO BOOKGENRES VALUES('4','3')
INSERT INTO BOOKGENRES VALUES('4','4')
INSERT INTO BOOKGENRES VALUES('4','7')
INSERT INTO BOOKGENRES VALUES('4','8')
INSERT INTO BOOKGENRES VALUES('4','41')

INSERT INTO BOOKGENRES VALUES('5','1')
INSERT INTO BOOKGENRES VALUES('5','2')
INSERT INTO BOOKGENRES VALUES('5','4')
INSERT INTO BOOKGENRES VALUES('5','6')
INSERT INTO BOOKGENRES VALUES('5','8')
INSERT INTO BOOKGENRES VALUES('5','9')

INSERT INTO BOOKGENRES VALUES('6','1')
INSERT INTO BOOKGENRES VALUES('6','2')
INSERT INTO BOOKGENRES VALUES('6','4')
INSERT INTO BOOKGENRES VALUES('6','5')
INSERT INTO BOOKGENRES VALUES('6','6')

