SET DATEFORMAT DMY;
USE HappiNovel

INSERT INTO GENRE VALUES('1',N'Truyện giả tưởng')
INSERT INTO GENRE VALUES('2',N'Truyện tình cảm')
INSERT INTO GENRE VALUES('3',N'Tài liệu')
INSERT INTO GENRE VALUES('4',N'Drama')
INSERT INTO GENRE VALUES('5',N'18+')
INSERT INTO GENRE VALUES('6',N'Học sinh')
INSERT INTO GENRE VALUES('7',N'Trinh thám')
INSERT INTO GENRE VALUES('8',N'Phiêu lưu')
INSERT INTO GENRE VALUES('9',N'Giật gân')
INSERT INTO GENRE VALUES('41',N'Châm biếm chính trị')