USE HappiNovel
SET DATEFORMAT DMY;

INSERT INTO NOTIFYOFUSER VALUES ('1','1')
INSERT INTO NOTIFYOFUSER VALUES ('1','2')
INSERT INTO NOTIFYOFUSER VALUES ('1','3')
INSERT INTO NOTIFYOFUSER VALUES ('1','4')
INSERT INTO NOTIFYOFUSER VALUES ('1','5')
INSERT INTO NOTIFYOFUSER VALUES ('1','6')
INSERT INTO NOTIFYOFUSER VALUES ('1','7')
INSERT INTO NOTIFYOFUSER VALUES ('1','8')
INSERT INTO NOTIFYOFUSER VALUES ('1','9')

INSERT INTO NOTIFYOFUSER VALUES ('40','1')
INSERT INTO NOTIFYOFUSER VALUES ('40','2')
INSERT INTO NOTIFYOFUSER VALUES ('40','3')
INSERT INTO NOTIFYOFUSER VALUES ('40','4')
INSERT INTO NOTIFYOFUSER VALUES ('40','5')
INSERT INTO NOTIFYOFUSER VALUES ('40','6')
INSERT INTO NOTIFYOFUSER VALUES ('40','7')
INSERT INTO NOTIFYOFUSER VALUES ('40','8')
INSERT INTO NOTIFYOFUSER VALUES ('40','9')

INSERT INTO NOTIFYOFUSER VALUES ('2','1')
INSERT INTO NOTIFYOFUSER VALUES ('6','1')
INSERT INTO NOTIFYOFUSER VALUES ('9','5')

INSERT INTO NOTIFYOFUSER VALUES ('3','2')
INSERT INTO NOTIFYOFUSER VALUES ('8','8')

INSERT INTO NOTIFYOFUSER VALUES ('4','1')
INSERT INTO NOTIFYOFUSER VALUES ('4','2')
INSERT INTO NOTIFYOFUSER VALUES ('4','7')

INSERT INTO NOTIFYOFUSER VALUES ('7','1')
INSERT INTO NOTIFYOFUSER VALUES ('7','2')
INSERT INTO NOTIFYOFUSER VALUES ('7','7')

INSERT INTO NOTIFYOFUSER VALUES ('5','1')
INSERT INTO NOTIFYOFUSER VALUES ('5','2')
INSERT INTO NOTIFYOFUSER VALUES ('5','7')



